name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      attest-package:
        description: "Create GitHub provenance attestation for the package."
        default: "false"
        type: string
    outputs:
      artifact-basename:
        description: "Base name of the uploaded artifacts; use for artifact retrieval."
        value: ${{ jobs.package.outputs.artifact-basename }}

# Cancel active CI runs for a PR before starting another run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash  # https://github.com/beeware/briefcase/pull/912

env:
  FORCE_COLOR: "1"

jobs:
  pre-commit:
    name: Pre-commit checks
    uses: beeware/.github/.github/workflows/pre-commit-run.yml@741cc5a311012ee0ee195938889a337449d01eeb  # main
    with:
      pre-commit-source: "--group pre-commit"

  package:
    name: Package xbuild
    needs: [ pre-commit ]
    permissions:
      id-token: write
      attestations: write
      contents: read
    uses: beeware/.github/.github/workflows/python-package-create.yml@741cc5a311012ee0ee195938889a337449d01eeb  # main
    with:
      attest: ${{ inputs.attest-package }}

  unit-tests:
    name: Unit tests
    needs: [ package ]
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.13", "3.14" ]

    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
        fetch-depth: 0
        # Nothing in this job pushes, so the token doesn't need to be
        # persisted in .git/config.
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
      with:
        python-version: "${{ matrix.python-version }}"
        allow-prereleases: true

    - name: Install test requirements
      run: |
        python -m pip install -U pip
        python -m pip install --group ci

    - name: Test
      run: |
        python -m tox -e py

    # # This step is only needed if you're trying to diagnose test failures that
    # # only occur in CI, and can't be reproduced locally. When it runs, it will
    # # open an SSH server (URL reported in the logs) so you can ssh into the CI
    # # machine.
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   if: failure()
